title: RCSC Fitness Centre
description: RCSC will provide a large, spacious training area, surrounded by a range of core and functional training equipment.

url: http://www.rcsc.fitness
baseurl: ""
paginate_path: "updates/page:num"
permalink: updates/:title

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /
  - title: Updates
    url: /updates
  - title: Subscribe
    url: /subscribe

social:
  facebook: rcscfitness
  email: studio@rcsc.fitness

google_analytics: "UA-155134939-1"
